chunkRenderPasses: 1
forcestars: false
fancyGraphics: true
cheatvoidFog: true
automatePerformance: false
fancyLight: true
showsky: true
farView: false
autosave: 0
clientLight: true
smoothFPS: true
time: 0
fastDebug: 0
randomMobTextures: true
mainMenuState: 1
chatOpacity: 0.5
fancyWater: true
betterGrass: 1
signDistance: 8
flightSpeedFactor: 1.0
waterBiomeColors: true
forceweather: false
fancyTrees: true
ambientOcclusion: true
replaceBlocks: true
brightnessSlider: 1.0
forcevoidFog: false
showHotbarText: true
forcesky: false
cheatclearWater: true
fancyBiomeColors: true
delayedTooltips: true
fancyClouds: true
showvoidFog: true
viewBobbing: false
chatColorAssist: true
advancedOpenGL: 1
aaSampling: 0
renderDistance: 1
showstars: true
replaceTools: true
cheatweather: true
mipmapsPercent: 1.0
connectedTextures: true
smoothLighting: 1.0
performance: 3
fancyParticles: true
advancedOptions: true
resizedScreenshotWidth: 6000
fancyGrass: true
showweather: true
forceclearWater: false
showclearWater: true
guiScale: 0
automateMode: 0
cheatstars: true
fancyFog: true
anaglyph3D: false
resizedScreenshotHeight: 3200
resizeScreenshots: false
cheatsky: true
serverTexturePromptsEnabled: true
fancyWeather: true
hotbarQuickKeysEnabled: true
